import React,{useState} from "react";
import {createRoot} from "react-dom/client";
import {BrowserRouter,useNavigate,useLocation,Routes,Route,Link} from "react-router-dom";
import {AnimatePresence,motion,useScroll,useSpring} from "framer-motion";
import {Menu,X,ArrowUpRight,Instagram,Facebook,PlayCircle,MessageCircle,ChevronDown,MapPin,Phone,Mail,Star,Send} from "lucide-react";
import "./styles.css";

const WA="59896174587", wa=`https://wa.me/${WA}?text=${encodeURIComponent("Hola, Shine by Susana. Me gustaría consultar sobre los servicios y disponibilidad para reservar una cita.")}`;
const images=[
"https://images.unsplash.com/photo-1604654894610-df63bc536371?auto=format&fit=crop&w=1200&q=85",
"https://images.unsplash.com/photo-1610992015732-2449b76344bc?auto=format&fit=crop&w=1000&q=85",
"https://images.unsplash.com/photo-1632345031435-8727f6897d53?auto=format&fit=crop&w=1000&q=85",
"https://images.unsplash.com/photo-1583001931096-959e9a1a6223?auto=format&fit=crop&w=1000&q=85",
"https://images.unsplash.com/photo-1519014816548-bf5fe059798b?auto=format&fit=crop&w=1000&q=85",
"https://images.unsplash.com/photo-1607779097040-26e80aa78e66?auto=format&fit=crop&w=1000&q=85",
"https://images.unsplash.com/photo-1599692047825-1d7b7df4a2f8?auto=format&fit=crop&w=1000&q=85",
"https://images.unsplash.com/photo-1610992015732-2449b76344bc?auto=format&fit=crop&w=1000&q=85",
"https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=1000&q=85",
"https://images.unsplash.com/photo-1604654894610-df63bc536371?auto=format&fit=crop&w=1000&q=85",
"https://images.unsplash.com/photo-1599948128020-9a44505b0d7d?auto=format&fit=crop&w=1000&q=85",
"https://images.unsplash.com/photo-1632345031435-8727f6897d53?auto=format&fit=crop&w=1000&q=85"
];
const reveal={hidden:{opacity:0,y:35},show:{opacity:1,y:0,transition:{duration:.75,ease:[.22,1,.36,1]}}};
const imgReveal={hidden:{opacity:0,scale:1.06},show:{opacity:1,scale:1,transition:{duration:.9,ease:[.22,1,.36,1]}}};

function Layout({children}){
 const [open,setOpen]=useState(false); const {scrollY}=useScroll(); const [scrolled,setScrolled]=useState(false);
 React.useEffect(()=>scrollY.on("change",v=>setScrolled(v>30)),[scrollY]);
 const nav=[["Inicio","/"],["Nosotros","/about"],["Servicios","/services"],["Galería","/gallery"],["Opiniones","/reviews"],["FAQ","/faq"],["Contacto","/contact"]];
 return <div className="site">
  <motion.header className={`nav ${scrolled?"nav-scrolled":""}`}><Link className="brand" to="/" onClick={()=>setOpen(false)}>SHINE <span>BY SUSANA</span></Link>
   <nav className="desktop-nav">{nav.map(([t,p])=><Link key={p} to={p}>{t}</Link>)}</nav>
   <Link className="nav-cta" to="/booking">Reservar cita <ArrowUpRight size={15}/></Link>
   <button className="menu-btn" aria-label="Abrir menú" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button>
  </motion.header>
  <AnimatePresence>{open&&<motion.div className="mobile-menu" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}>{nav.map(([t,p],i)=><motion.div key={p} initial={{y:30,opacity:0}} animate={{y:0,opacity:1}} transition={{delay:i*.05}}><Link to={p} onClick={()=>setOpen(false)}>{t}</Link></motion.div>)}<Link className="mobile-book" to="/booking" onClick={()=>setOpen(false)}>Reservar cita <ArrowUpRight/></Link></motion.div>}</AnimatePresence>
  <main>{children}</main>
  <Footer/>
  <a className="wa-float" href={wa} target="_blank" rel="noreferrer" aria-label="Escribir por WhatsApp"><MessageCircle size={22}/><span>¿Tienes alguna pregunta?</span></a>
 </div>
}

function Footer(){return <footer><div className="footer-top"><div><div className="footer-logo">SHINE <span>BY SUSANA</span></div><p>Nail art, cuidado y estilo en Montevideo.</p></div><div className="footer-col"><b>Explorar</b><Link to="/">Inicio</Link><Link to="/about">Nosotros</Link><Link to="/services">Servicios</Link><Link to="/gallery">Galería</Link><Link to="/reviews">Opiniones</Link><Link to="/faq">FAQ</Link></div><div className="footer-col"><b>Reservas</b><Link to="/booking">Reservar cita</Link><a href={wa}>WhatsApp</a><Link to="/contact">Contacto</Link></div><div className="footer-col"><b>Síguenos</b><a href="#" aria-label="Instagram"><Instagram size={18}/> Instagram</a><a href="#" aria-label="Facebook"><Facebook size={18}/> Facebook</a><a href="#">TikTok</a><a href="#">YouTube</a></div></div><div className="footer-bottom"><span>© 2026 Shine by Susana. Todos los derechos reservados.</span><span>Montevideo, Uruguay · <a href="https://wa.me/59896174587">+598 96 174 587</a></span></div><div className="powered">Powered by <strong>TCP IT Solution</strong></div></footer>}

function PageHead({eyebrow,title,text}){return <section className="page-head"><div className="eyebrow">{eyebrow}</div><motion.h1 initial={{opacity:0,y:25}} animate={{opacity:1,y:0}}>{title}</motion.h1>{text&&<p>{text}</p>}</section>}
function SectionTitle({eyebrow,title,text}){return <div className="section-title"><div className="eyebrow">{eyebrow}</div><h2>{title}</h2>{text&&<p>{text}</p>}</div>}
function Button({to,label="Reservar cita",ghost=false}){return <Link className={`btn ${ghost?"btn-ghost":""}`} to={to}>{label}<ArrowUpRight size={17}/></Link>}

function Home(){
 return <><section className="hero"><div className="hero-media"><motion.img src={images[0]} alt="Manicure elegante en tonos nude" variants={imgReveal} initial="hidden" animate="show"/></div><div className="hero-copy"><div className="eyebrow">NAIL ART · MONTEVIDEO</div><h1>Brilla con<br/><em>tu propio</em> estilo.</h1><p>Manicura, nail art y belleza cuidada hasta el último detalle.</p><div className="hero-actions"><Button to="/booking"/><Button to="/services" label="Descubrir servicios" ghost/></div></div><div className="scroll-note">SCROLL TO DISCOVER <span></span></div></section>
 <section className="trust"><div><strong>5.0 <Star size={17} fill="currentColor"/></strong><span>Google Rating</span></div><div><strong>1</strong><span>Opinión verificada</span></div><div><strong>100%</strong><span>Atención personalizada</span></div><div><strong>MONTEVIDEO</strong><span>Uruguay</span></div></section>
 <section className="about-preview container"><div className="about-image"><motion.img src={images[3]} alt="Detalle de manicura" variants={imgReveal} initial="hidden" whileInView="show" viewport={{once:true}}/></div><motion.div className="about-copy" variants={reveal} initial="hidden" whileInView="show" viewport={{once:true}}><div className="eyebrow">SHINE BY SUSANA</div><h2>Tu momento<br/><em>de brillo.</em></h2><p>Shine by Susana nace para convertir el cuidado de tus uñas en una experiencia especial, cuidada y personalizada.</p><p>Una propuesta creada alrededor del detalle, el estilo y el cuidado personal.</p><Button to="/about" label="Conocer más" ghost/></motion.div></section>
 <section className="experience"><div className="container"><SectionTitle eyebrow="THE SHINE EXPERIENCE" title="Una experiencia pensada para ti" text="Cada visita empieza con tu estilo y termina en un detalle que se siente propio."/><div className="steps">{[["01","Descubre","Conoce nuestras opciones y encuentra el estilo que mejor representa tu personalidad."],["02","Personaliza","Elige forma, color, acabado y detalles."],["03","Brilla","Disfruta de un resultado cuidado y pensado para ti."]].map(([n,t,d])=><motion.div className="step" key={n} variants={reveal} initial="hidden" whileInView="show" viewport={{once:true}}><span>{n}</span><h3>{t}</h3><p>{d}</p></motion.div>)}</div></div></section>
 <section className="feature container"><div className="feature-image"><motion.img src={images[2]} alt="Nail art elegante" variants={imgReveal} initial="hidden" whileInView="show" viewport={{once:true}}/><span>SHINE DETAIL</span></div><div className="feature-copy"><div className="eyebrow">NAIL ART</div><h2>Pequeños detalles.<br/><em>Gran diferencia.</em></h2><p>Diseños cuidadosamente realizados para complementar tu estilo y convertir cada manicure en una expresión personal.</p><Button to="/gallery" label="Ver galería" ghost/></div></section>
 <section className="inspiration"><div className="container"><SectionTitle eyebrow="INSPIRACIÓN" title="Una mirada a tu próximo estilo" text="Explora algunos estilos y detalles de nail art."/><div className="mini-gallery">{images.slice(0,6).map((im,i)=><Link to="/gallery" className="mini-item" key={i}><motion.img src={im} alt={`Inspiración de nail art ${i+1}`} variants={imgReveal} initial="hidden" whileInView="show" viewport={{once:true}} transition={{delay:i*.07}}/><span>Ver detalle <ArrowUpRight size={14}/></span></Link>)}</div><div className="center"><Button to="/gallery" label="Explorar galería" ghost/></div></div></section>
 <section className="review-strip"><div className="container review-inner"><div><div className="eyebrow">GOOGLE</div><h2>Una experiencia que<br/><em>queremos que recuerdes.</em></h2></div><div className="rating"><strong>5.0 <Star fill="currentColor"/></strong><span>1 reseña</span><p>“Excelente experiencia.”</p><small>Gabriela Garcia · 5 estrellas</small><a href="#" className="text-link">Ver opiniones en Google <ArrowUpRight size={15}/></a></div></div></section>
 <section className="cta-band"><div className="eyebrow">MONTEVIDEO · URUGUAY</div><h2>Tu próximo detalle<br/><em>empieza aquí.</em></h2><Button to="/booking"/></section></>
}

function About(){return <><PageHead eyebrow="NOSOTROS" title={<>El lujo está en<br/><em>el detalle.</em></>} text="Una propuesta de nail beauty donde el estilo y el cuidado personal se encuentran."/><section className="editorial container"><motion.img src={images[4]} alt="Manicura en estudio" variants={imgReveal} initial="hidden" whileInView="show" viewport={{once:true}}/><div><div className="eyebrow">SHINE BY SUSANA</div><h2>Un espacio para<br/><em>sentirte tú.</em></h2><p>Shine by Susana está pensado alrededor de una idea sencilla: que el cuidado de tus uñas pueda sentirse especial. Manicure, nail art y atención personalizada se unen en una experiencia de boutique.</p><p>Sin prisas, sin exceso. Solo detalles elegidos para acompañar tu estilo.</p><div className="signature">SHINE <span>BY SUSANA</span></div></div></section><section className="quote-section"><div className="container"><p>“Una propuesta creada alrededor del detalle, el estilo y el cuidado personal.”</p></div></section></>}

const services=[["Manicure","Manicura clásica, premium y cuidado de uñas.","Consultar"],["Nail Art","Diseños personalizados, minimalistas y detalles especiales.","Consultar"],["Gel / Semi-Permanent","Gel y esmaltado semipermanente con acabados premium.","Consultar"]];
function Services(){return <><PageHead eyebrow="SERVICIOS" title={<>Belleza, cuidado<br/><em>y creatividad.</em></>} text="Opciones diseñadas para que encuentres el acabado que más se parece a ti."/><section className="services-grid container">{services.map((s,i)=><motion.article className="service-card" key={s[0]} variants={reveal} initial="hidden" whileInView="show" viewport={{once:true}}><div className="service-img"><motion.img src={images[i+1]} alt={s[0]} variants={imgReveal} initial="hidden" whileInView="show" viewport={{once:true}}/><span>DEMO</span></div><div className="service-body"><div className="eyebrow">SERVICIO {String(i+1).padStart(2,"0")}</div><h2>{s[0]}</h2><p>{s[1]}</p><Link to="/booking">{s[2]} <ArrowUpRight size={16}/></Link></div></motion.article>)}</section><div className="demo-note container">Contenido de demostración · Los nombres detallados, duración y precios deberán ser confirmados y reemplazados por la información oficial de Shine by Susana antes del lanzamiento.</div></>}

function Gallery(){const [selected,setSelected]=useState(null);return <><PageHead eyebrow="GALERÍA" title={<>Inspiración<br/><em>en cada detalle.</em></>} text="Una selección visual para descubrir colores, acabados y estilos."/><section className="gallery container">{images.map((im,i)=><motion.button className={`gallery-item gi-${i%5}`} key={i} onClick={()=>setSelected(im)} variants={reveal} initial="hidden" whileInView="show" viewport={{once:true}}><motion.img src={im} alt={`Nail art y manicure ${i+1}`} variants={imgReveal} initial="hidden" whileInView="show" viewport={{once:true}}/><span>Ver detalle <ArrowUpRight size={15}/></span></motion.button>)}</section>{selected&&<motion.div className="lightbox" initial={{opacity:0}} animate={{opacity:1}} onClick={()=>setSelected(null)}><button aria-label="Cerrar"><X/></button><img src={selected} alt="Detalle de nail art ampliado"/></motion.div>}</>}

function Reviews(){return <><PageHead eyebrow="OPINIONES" title={<>Lo que dicen<br/><em>nuestras clientas.</em></>} text="La voz de nuestras clientas es parte de la experiencia Shine."/><section className="reviews-page container"><div className="big-rating"><strong>5.0</strong><div>★★★★★</div><span>Google · 1 reseña</span></div><article className="review-card"><div className="review-top"><div className="avatar">G</div><div><b>Gabriela Garcia</b><small>Google · reseña verificada</small></div><div className="stars">★★★★★</div></div><p>“Excelente experiencia.”</p></article><div className="demo-review"><span>TESTIMONIO DEMO</span><p>“Tu experiencia puede aparecer aquí.”</p><small>Demo content — reemplazar con reseñas reales</small></div></section></>}

const faqs=[["¿Cómo puedo reservar una cita?","Puedes solicitar tu cita desde nuestro formulario de reservas o contactarnos directamente por WhatsApp."],["¿Qué servicios ofrecen?","Ofrecemos servicios relacionados con manicura, cuidado de uñas y nail art. Consulta disponibilidad y opciones antes de reservar."],["¿Puedo solicitar un diseño personalizado?","Sí. Puedes indicar tus preferencias y referencias al solicitar tu cita."],["¿Dónde están ubicados?","Estamos en Montevideo, Uruguay."],["¿Cómo puedo consultar disponibilidad?","Puedes escribirnos directamente por WhatsApp o enviar una solicitud desde la página de reservas."],["¿Puedo enviar una referencia del diseño?","Añadir una futura opción para adjuntar una imagen de referencia al formulario."]];
function FAQ(){const [active,setActive]=useState(null);return <><PageHead eyebrow="FAQ" title={<>Todo lo que<br/><em>quieras saber.</em></>} text="Respuestas rápidas antes de tu próxima visita."/><section className="faq container">{faqs.map(([q,a],i)=><div className={`faq-row ${active===i?"active":""}`} key={q}><button onClick={()=>setActive(active===i?null:i)}><span>{q}</span><ChevronDown/></button><AnimatePresence>{active===i&&<motion.div initial={{height:0,opacity:0}} animate={{height:"auto",opacity:1}} exit={{height:0,opacity:0}}><p>{a}</p></motion.div>}</AnimatePresence></div>)}</section></>}

function Booking(){const [sent,setSent]=useState(false);return <><PageHead eyebrow="RESERVA" title={<>Reserva<br/><em>tu cita.</em></>} text="Cuéntanos qué estilo tienes en mente y nos pondremos en contacto contigo para confirmar disponibilidad."/><section className="booking container"><div className="form-wrap">{sent?<motion.div className="success" initial={{opacity:0,y:15}} animate={{opacity:1,y:0}}><div className="success-mark">✓</div><h2>¡Gracias!</h2><p>Hemos recibido tu solicitud. Nos pondremos en contacto contigo para confirmar tu cita.</p><Button to="/" label="Volver al inicio" ghost/></motion.div>:<form onSubmit={e=>{e.preventDefault();setSent(true)}}><div className="form-grid"><label>Nombre<input required placeholder="Tu nombre"/></label><label>Teléfono<input required placeholder="+598 ..."/></label><label>Email<input type="email" placeholder="tu@email.com"/></label><label>Servicio<select><option>Seleccionar servicio</option><option>Manicure</option><option>Nail Art</option><option>Gel / Semi-Permanent</option></select></label><label>Fecha preferida<input type="date"/></label><label>Hora preferida<input type="time"/></label></div><label>Diseño / preferencias<textarea rows="4" placeholder="Cuéntanos qué tienes en mente..."/></label><label>Mensaje<textarea rows="4" placeholder="Algo más que quieras contarnos..."/></label><button className="btn submit" type="submit">Solicitar cita <Send size={16}/></button></form>}</div><aside className="booking-side"><div className="eyebrow">¿PREFIERES WHATSAPP?</div><h2>Hablemos<br/><em>directamente.</em></h2><p>Para consultas rápidas sobre servicios y disponibilidad, escríbenos.</p><a className="btn" href={wa} target="_blank" rel="noreferrer">Reservar por WhatsApp <MessageCircle size={17}/></a></aside></section></>}

function Contact(){return <><PageHead eyebrow="CONTACTO" title={<>Hablemos.</>} text="¿Tienes un diseño en mente? Estamos aquí para ayudarte."/><section className="contact-grid container"><div className="contact-info"><div className="contact-card"><Phone/><span>WHATSAPP</span><a href={wa}>+598 96 174 587</a></div><div className="contact-card"><MapPin/><span>UBICACIÓN</span><p>13000 Montevideo<br/>Montevideo Department<br/>Uruguay</p></div><div className="contact-card"><Star/><span>GOOGLE</span><p>5V3P+XF Montevideo</p></div></div><div className="contact-form"><h2>Envíanos un mensaje.</h2><form onSubmit={e=>e.preventDefault()}><input required placeholder="Nombre"/><input required type="email" placeholder="Email"/><input placeholder="Teléfono"/><textarea required rows="6" placeholder="Mensaje"></textarea><button className="btn">Enviar mensaje <Send size={16}/></button></form></div></section><section className="map-section container"><div><div className="eyebrow">MONTEVIDEO</div><h2>Nos encontramos<br/><em>en Montevideo.</em></h2><p>13000 Montevideo, Montevideo Department, Uruguay</p><a className="btn btn-ghost" href="https://www.google.com/maps/search/?api=1&query=5V3P%2BXF%20Montevideo" target="_blank" rel="noreferrer">Cómo llegar <ArrowUpRight size={17}/></a></div><div className="map"><iframe title="Mapa de Montevideo" src="https://www.google.com/maps?q=5V3P%2BXF%20Montevideo&output=embed" loading="lazy"></iframe></div></section></>}

function App(){const loc=useLocation(); return <Layout><AnimatePresence mode="wait"><motion.div key={loc.pathname} initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} transition={{duration:.28}}><Routes location={loc}><Route path="/" element={<Home/>}/><Route path="/about" element={<About/>}/><Route path="/services" element={<Services/>}/><Route path="/gallery" element={<Gallery/>}/><Route path="/reviews" element={<Reviews/>}/><Route path="/faq" element={<FAQ/>}/><Route path="/booking" element={<Booking/>}/><Route path="/contact" element={<Contact/>}/></Routes></motion.div></AnimatePresence></Layout>}
createRoot(document.getElementById("root")).render(<BrowserRouter><App/></BrowserRouter>);